name: $(Date:yyyMMdd).$(Rev:r)
jobs:
- job: VS_Code_Release
  pool:
    name: VSEng-MicroBuildVS2019
  variables:
    TEST_LAB_BUILD: 'true' # REMOVE when we use 'real' sign
  steps:
  - task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@2
    displayName: 'Install Signing Plugin'
    inputs:
      signType: test

  - task: ms-vseng.MicroBuildTasks.a0262b21-fb8f-46f8-bb9a-60ed560d4a87.MicroBuildLocalizationPlugin@2
    displayName: 'Install Localization Plugin'

  - task: NuGetInstaller@0
    displayName: 'NuGet restore src/MIDebugEngine.sln'
    inputs:
      solution: src/MIDebugEngine.sln
      nuGetPath: '$(Build.SourcesDirectory)\tools\NuGet\nuget.exe'

  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'

  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
      configuration: 'Desktop.Debug'

  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
      configuration: 'Desktop.Release'

  - task: PublishSymbols@1
    displayName: 'Index Sources'
    inputs:
      SymbolsPath: '$(DropRoot)\$(TeamName)\symbols'
      SearchPattern: '**\*.pdb'
      SymbolsFolder: '$(Build.BinariesDirectory)'
      SkipIndexing: true
    continueOnError: true

  - task: CopyFiles@2
    displayName: 'Collect build symbols'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '$(Build.SourcesDirectory)\bin\**\*.+(pdb|exe|dll)'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/symbols'
      CleanTargetFolder: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Symbols'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/symbols'
      ArtifactName: Symbols

  - task: CopyPublishBuildArtifacts@1
    displayName: 'Publish Drop'
    inputs:
      CopyRoot: '$(Build.BinariesDirectory)'
      Contents: '**'
      ArtifactName: drop
      ArtifactType: FilePath
      TargetPath: '$(DropRoot)\$(TeamName)\$(Build.DefinitionName)\$(Build.BuildNumber)'
    condition: succeededOrFailed()

  - task: ms-vseng.MicroBuildTasks.bd4b789e-7292-4b73-a8ee-612d3dd615f1.MicroBuildStaticDrop@1
    displayName: 'Update Static Drop'
    inputs:
      CopyRoot: '$(Build.BinariesDirectory)'
      Contents: '**'
      TargetPath: '$(DropRoot)\$(TeamName)\$(Build.DefinitionName)\latest\$(BuildConfiguration)'

  - task: ms-vseng.MicroBuildTasks.521a94ea-9e68-468a-8167-6dcf361ea776.MicroBuildCleanup@1
    displayName: 'Perform Cleanup Tasks'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish MicroBuild Outputs'
    inputs:
      PathtoPublish: '$(Build.StagingDirectory)\MicroBuild\Output'
      ArtifactName: MicroBuildOutputs
      publishLocation: FilePath
      TargetPath: '$(DropRoot)\$(TeamName)\$(Build.DefinitionName)\$(Build.BuildNumber)'
    condition: succeededOrFailed()

  - task: NuGetPackager@0
    displayName: 'NuGet Packager '
    inputs:
      searchPattern: 'MIEngine.mdd.nuspec;MIEngine.UnixPortSupplier.nuspec'
      versionByBuild: byEnvVar
      versionEnvVar: 'BUILD_BUILDNUMBER'
      configurationToPack: Release
      nuGetAdditionalArgs: '/BasePath $(DropRoot)\$(TeamName)\$(Build.DefinitionName)\$(Build.BuildNumber)'

  - task: NuGetPublisher@0
    displayName: 'NuGet Publisher '
    inputs:
      searchPattern: 'VS.Redist.Debugger.MDD.MIEngine.*.nupkg;VS.Redist.Debugger.MDD.UnixPortSupplier.*.nupkg'
      nuGetFeedType: internal
      feedName: 'https://devdiv.pkgs.visualstudio.com/DefaultCollection/_packaging/VS/nuget/v3/index.json'
