name: $(Date:yyyMMdd).$(Rev:r)
jobs:
- job: VS_Code_Release
  pool:
    name: VSEng-MicroBuildVS2019
  steps:
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet'

  - task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@2
    displayName: 'Install Signing Plugin'
    inputs:
      signType: test

  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'

  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
      configuration: 'Desktop.Release'
      msbuildArguments: '/p:Lab=$(Lab)'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Binaries'
    inputs:
      targetPath: '$(Build.BinariesDirectory)' 
      artifactName: 'bin'

  # Collect and Publish Symbols
  - task: CopyFiles@2
    displayName: 'Collect build symbols'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '$(Build.SourcesDirectory)\bin\**\*.+(pdb|exe|dll)'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/symbols'
      CleanTargetFolder: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Symbols'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/symbols' 
      artifactName: 'Symbols'