name: $(Date:yyyMMdd).$(Rev:r)
jobs:
- job: VS_Code_Release
  pool:
    name: VSEng-MicroBuildVS2019
  steps:
  - task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@2
    displayName: 'Install Signing Plugin'
    inputs:
      signType: test

  - task: NuGetInstaller@0
    displayName: 'NuGet restore src/MIDebugEngine.sln'
    inputs:
      solution: src/MIDebugEngine.sln
      nuGetPath: '$(Build.SourcesDirectory)\tools\NuGet\nuget.exe'

  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'

  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
      configuration: 'Desktop.Release'
      msbuildArguments: '/p:Lab=$(Lab)'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Binaries'
    inputs:
      targetPath: '$(Build.BinariesDirectory)' 
      artifactName: 'bin'