name: $(Date:yyyMMdd).$(Rev:r)
jobs:
- job: VS_Code_Release
  pool:
    name: VSEng-MicroBuildVS2019
  steps:
  - task: NuGetInstaller@0
    displayName: 'NuGet restore src/MIDebugEngine.sln'
    inputs:
      solution: src/MIDebugEngine.sln
      nuGetPath: '$(Build.SourcesDirectory)\tools\NuGet\nuget.exe'

  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'

  - task: VSBuild@1
    displayName: 'Build Solution **\*.sln'
    inputs:
      solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
      msbuildArgs: '/p:Lab=$(Lab) /v:diag'
      platform: 'Any CPU'
      configuration: 'Desktop.Release'
      clean: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Binaries'
    inputs:
      targetPath: '$(Build.BinariesDirectory)' 
      artifactName: # 'bin'