name: $(Date:yyyMMdd).$(Rev:r)
jobs:
- job: VS_Release
  pool:
    name: VSEng-MicroBuildVS2019
  steps:
  - template: ./tasks/NuGetToolInstaller.yml

  - task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@2
    displayName: 'Install Signing Plugin'
    inputs:
      signType: test

  - task: ms-vseng.MicroBuildTasks.a0262b21-fb8f-46f8-bb9a-60ed560d4a87.MicroBuildLocalizationPlugin@2
    displayName: 'Install Localization Plugin'

  - template: ./steps/BuildSolution.yml

  - template: ./steps/CollectAndPublishBinaries.yml
    parameters:
      TargetFolder: '$(Build.StagingDirectory)\drop'
      ArtifactName: 'drop'

  - template: ./steps/CopyAndPublishSymbols.yml

  - template: ./steps/PackAndPublishVSPackages.yml

  - task: ms-vseng.MicroBuildTasks.521a94ea-9e68-468a-8167-6dcf361ea776.MicroBuildCleanup@1
    displayName: 'Perform Cleanup Tasks'