name: $(Date:yyyMMdd).$(Rev:r)
jobs:
- job: VS_Code_Release
  pool:
    name: VSEng-MicroBuildVS2019
  steps:
  - template: ./tasks/NuGetToolInstall.yml

  - task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@2
    displayName: 'Install Signing Plugin'
    inputs:
      signType: test

  - template: ./steps/BuildSolution.yml
    parameters:
      Configuration: 'Desktop.Release'
      BuildArguments: '/p:Lab=$(Lab)'

  - template: ./steps/CollectAndPublishBinaries.yml
    parameters:
      TargetFolder: '$(Build.StagingDirectory)\bin'
      ArtifactName: 'bin'

  - template: ./steps/CopyAndPublishSymbols.yml
  
  - task: ms-vseng.MicroBuildTasks.521a94ea-9e68-468a-8167-6dcf361ea776.MicroBuildCleanup@1
    displayName: 'Perform Cleanup Tasks'