name: $(Date:yyyMMdd).$(Rev:r)
jobs:
- job: VS_Code_Release
  pool:
    name: VSEng-MicroBuildVS2019
  steps:
  - checkout: self

  - template: ./tasks/NuGetToolInstaller.yml

  -template: ./tasks/MicroBuildSigningPlugin.yml

  - template: ./steps/BuildSolution.yml
    parameters:
      Configuration: 'Desktop.Release'
      BuildArguments: '/p:Lab=$(Lab)'

  - template: ./steps/CollectAndPublishBinaries.yml
    parameters:
      TargetFolder: '$(Build.StagingDirectory)\bin'
      ArtifactName: 'bin'

  - template: ./steps/CopyAndPublishSymbols.yml

  - template: ./tasks/MicroBuildCleanup.yml