parameters:
  JobName: 'VSEng-MicroBuildVS2019'
  BuildTemplate: ''

jobs:
- job: ${{ parameters.JobName }}
  pool:
    name: VSEng-MicroBuildVS2019
  steps:
  - template: ../templates/${{ paramters.BuildTemplate }}.template.yml